# 配置文件
#by @Oreomeow
#有些脚本未进库配置也没什么用
# cookie 以实际获取为准，如遇到带双引号的需用 \ 转义，或改为单引号，或将最外层双引号改为单引号
# e.g.1 cookie = "xxx; app_param={\"brand\":\"iPhone\"}"
# e.g.2 cookie = "xxx; app_param={'brand':'iPhone'}"
# e.g.3 cookie = 'xxx; app_param={"brand":"iPhone"}'

## 爱企查e卡监控
#ECARDCHECK = false
#
## Hax 监控
#HAX = false
#
## LeetCode 每日一题
#LEETCODE = false
#
## 每日一句
#MOTTO = true
#
## 每日新闻
#NEWS = true
#
## 青龙随机定时
#QL_RANDOM_TIME = false
#
## 天气预报
#CITY = ["上海", "朝阳区"]

# AcFun
# https://www.acfun.cn
######### 多账号示例 #########
[[ACFUN]]
password = "Sitoi"
phone = "188xxxxxxxx"
[[ACFUN]]
password = "123456"
phone = "135xxxxxxxx"
######### 多账号示例 #########

# 机场签到
# 邮箱
# 密码
# 链接，只支持 SSPanel 类型。删除 /auth/login
[[AIRPORT]]
email = "xxxxxxxx@qq.com"
password = "xxxxxxxx"
url = "https://xxxxxxxx.xxx"

# 爱企查【WEB】
# https://www.baidu.com，同百度贴吧 cookie 一样
# 批量查询任务需手动抓包查询之后的 exportkey，可不填
[[AQC]]
cookie = 'log_guid=xxxxxx; BDPPN=xxx"xxx;...'
exportkey = ""


[[PT]]
site = '阿童木'
url = "https://hdatmos.club/attendance.php"
referer = "https://hdatmos.club/index.php"
cookie = "XXX"

